---
title: "Bubup Wilam"
output:
  html_document: default
  pdf_document: default
---

```{r}
library(RODBC)
library(dplyr)
library(plyr)
Best_Practice <- odbcConnect("ODBC_BP", uid = "BPSRAWDATA", pwd = "Loma77")

Patients = sqlFetch(Best_Practice,"BPS_Patients")

Actions = sqlFetch(Best_Practice,"BPS_Actions") 

Alcohol = sqlFetch(Best_Practice,"BPS_Alcohol") 

All_Actions = sqlFetch(Best_Practice,"BPS_All_Actions")

All_History = sqlFetch(Best_Practice,"BPS_All_History")

AllHistory = sqlFetch(Best_Practice,"BPS_AllHistory")

All_Immunisation = sqlFetch(Best_Practice,"BPS_All_Immunisations")

All_Observations = sqlFetch(Best_Practice,"BPS_All_Observations")

Observations = sqlFetch(Best_Practice,"BPS_Observations")

All_PapSmears = sqlFetch(Best_Practice,"BPS_All_PapSmears")

PapSmears = sqlFetch(Best_Practice,"BPS_PapSmears")

Parameters = sqlFetch(Best_Practice,"BPS_Parameters")

All_Parameters = sqlFetch(Best_Practice,"BPS_All_Parameters")

All_Pregnancies = sqlFetch(Best_Practice,"BPS_All_Pregnancies")

Pregnancies = sqlFetch(Best_Practice,"BPS_Pregnancies")

All_Prescriptions = sqlFetch(Best_Practice,"BPS_All_Prescriptions")

Prescriptions = sqlFetch(Best_Practice,"BPS_Prescriptions")

Reminders = sqlFetch(Best_Practice,"BPS_Reminders")

All_Reminders = sqlFetch(Best_Practice,"BPS_All_Reminders")

All_Requests = sqlFetch(Best_Practice,"BPS_All_Requests")

Requests = sqlFetch(Best_Practice,"BPS_Requests")

Antenatal_Visits = sqlFetch(Best_Practice,"BPS_AntenatalVisits")

Appointments = sqlFetch(Best_Practice,"BPS_Appointments")

Births = sqlFetch(Best_Practice,"BPS_Births")

Clinical = sqlFetch(Best_Practice,"BPS_Clinical")

Clinical_images = sqlFetch(Best_Practice,"BPS_ClinicalImages")

Contact_Address = sqlFetch(Best_Practice,"BPS_ContactAddresses")

COntacts = sqlFetch(Best_Practice,"BPS_Contacts") 

CorrespondenceIn = sqlFetch(Best_Practice,"BPS_CorrespondenceIn")

CorrespondenceOut = sqlFetch(Best_Practice,"BPS_CorrespondenceOut")

CurrentRx = sqlFetch(Best_Practice,"BPS_CurrentRx")

DaysAway = sqlFetch(Best_Practice,"BPS_DaysAway")

DbVersion = sqlFetch(Best_Practice,"BPS_DbVersion")

Diabetes = sqlFetch(Best_Practice,"BPS_Diabetes")

EPCReports = sqlFetch(Best_Practice,"BPS_EPCReports")

Extra_Sessions = sqlFetch(Best_Practice,"BPS_ExtraSessions")

Family_History = sqlFetch(Best_Practice,"BPS_FamilyHistory") 

Family_History_Detail = sqlFetch(Best_Practice,"BPS_FamilyHistoryDetail")

History = sqlFetch(Best_Practice,"BPS_History") 

Obser_Gyno = sqlFetch(Best_Practice,"BPS_ObsGyn") 

Occupation_history = sqlFetch(Best_Practice,"BPS_OccupationHistory") 

Patients_Login = sqlFetch(Best_Practice,"BPS_PatientLogin")

Practice_Locations = sqlFetch(Best_Practice,"BPS_PracticeLocations")

Reactions = sqlFetch(Best_Practice,"BPS_Reactions")

Report_Values = sqlFetch(Best_Practice,"BPS_ReportValues")

Services = sqlFetch(Best_Practice,"BPS_Services")

Sessions = sqlFetch(Best_Practice,"BPS_Sessions")

Tobacco = sqlFetch(Best_Practice,"BPS_Tobacco")

Users = sqlFetch(Best_Practice,"BPS_Users")

Visit_Reason =sqlFetch(Best_Practice,"BPS_VisitReason")

Visits = sqlFetch(Best_Practice,"BPS_Visits")
```

```{r}
# Number of Patients / Number of Active Patients
# Patients table contains details related to the patients with unique Internal ID which is the patient ID in the Best Practice.
# No. of patients are the same as active patients as they haven't segregated them.

Total_Patients <- length(unique(Patients$InternalID))
Total_Patients
```               
```{r}
# Total number of consultations by clinicians
Clinician <- count(Visits$DrName)  
Clinician

Clinician %>% group_by %>% summarise(Total= log(sum(freq)))
```

```{r}
#Total Number of active patients by clinicians
Providers <- count(Appointments$Provider)
Providers
class(Visits)
```


```{r}
# Total number of consultations based on the type
Consultations <- count(Appointments$AppointmentType)
Consultations
```

```{r}
# Summary table for the services based on their description
Service <- count(Services$DESCRIPTION)
Service
```

```{r}
#Total Number of MBS Item codes 
Total_MBS_Item <- length(unique(Services$MBSITEM))
Total_MBS_Item

#Total Number of MBS Item Codes by MBS Item Codes
MBS_Item <- count(Services$MBSITEM)
MBS_Item
```

```{r trial, echo=FALSE} 
#Trial
Sessions_Time <- Sessions %>% select(-StartDate,-EndDate,-Day,-Provider)
Sessions_Time


Duration_session <- Sessions_Time %>% mutate_all(funs(./60/60)) %>% select(-Length)
Duration_session

```
